// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Voltei.Api.Data;

#nullable disable

namespace Voltei.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417213325_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Voltei.Api.Models.AppleDeviceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceLibraryIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassTypeIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceLibraryIdentifier", "PassTypeIdentifier", "SerialNumber")
                        .IsUnique();

                    b.ToTable("AppleDeviceRegistrations");
                });

            modelBuilder.Entity("Voltei.Api.Models.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoresPrimaria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoresSecundaria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Plano")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("Voltei.Api.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplePassTypeId")
                        .HasColumnType("text");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int>("CheckinsNecessarios")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WalletClassId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Voltei.Api.Models.CheckinLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParticipacaoId");

                    b.HasIndex("RegistradoPor");

                    b.ToTable("CheckinLogs");
                });

            modelBuilder.Entity("Voltei.Api.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Voltei.Api.Models.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplePassAuthToken")
                        .HasColumnType("text");

                    b.Property<string>("ApplePassSerial")
                        .HasColumnType("text");

                    b.Property<string>("ApplePushToken")
                        .HasColumnType("text");

                    b.Property<Guid>("CampanhaId")
                        .HasColumnType("uuid");

                    b.Property<int>("CheckinsAtuais")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Resgatou")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WalletObjectId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("CampanhaId", "ClienteId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Voltei.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NegocioId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Voltei.Api.Models.Campaign", b =>
                {
                    b.HasOne("Voltei.Api.Models.Business", "Negocio")
                        .WithMany("Campaigns")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Voltei.Api.Models.CheckinLog", b =>
                {
                    b.HasOne("Voltei.Api.Models.Enrollment", "Participacao")
                        .WithMany("CheckinLogs")
                        .HasForeignKey("ParticipacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Voltei.Api.Models.User", "Staff")
                        .WithMany()
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participacao");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Voltei.Api.Models.Enrollment", b =>
                {
                    b.HasOne("Voltei.Api.Models.Campaign", "Campanha")
                        .WithMany("Enrollments")
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Voltei.Api.Models.Customer", "Cliente")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Voltei.Api.Models.User", b =>
                {
                    b.HasOne("Voltei.Api.Models.Business", "Negocio")
                        .WithMany("Users")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Voltei.Api.Models.Business", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Voltei.Api.Models.Campaign", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Voltei.Api.Models.Customer", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Voltei.Api.Models.Enrollment", b =>
                {
                    b.Navigation("CheckinLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
