service: voltei

image: lobosque/fidelitas

servers:
  web:
    hosts:
      - 20.1.176.90
    proxy:
      ssl: true
      host: staging.voltei.velvet.dev.br
      app_port: 3000

registry:
  server: ghcr.io
  username: lobosque
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: .
  dockerfile: Dockerfile

env:
  clear:
    ASPNETCORE_ENVIRONMENT: Production
    ASPNETCORE_URLS: http://+:3000
    AppleWallet__CertificatePath: /app/certs/pass-cert.p12
    AppleWallet__WebServiceUrl: https://staging.voltei.velvet.dev.br/api/apple-wallet
  secret:
    - DATABASE_URL
    - JWT_SECRET
    - GoogleWallet__IssuerId
    - GoogleWallet__ServiceAccountEmail
    - GoogleWallet__ServiceAccountPrivateKey
    - AppleWallet__PassTypeIdentifier
    - AppleWallet__TeamIdentifier
    - AppleWallet__CertificatePassword

ssh:
  user: voltei
